vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       lots_image:
           uri_prefix: /uploads/lot/
           upload_destination: '%upload_directory_lots%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
